import Header from '@/components/Header';
import HeroSection from '@/components/HeroSection';
import ProductSection from '@/components/ProductSection';
import Footer from '@/components/Footer';

/**
 * Home Page
 * Minimalist Brutalism Design
 * - Complete homepage replication of zeelproject.com
 * - Responsive layout with clean typography
 * - Product grids for Models, Scenes, Textures, and Works
 */

// Sample data for 3D Models
const modelsData = [
  {
    id: '1',
    image: '/images/model-vortex.jpg',
    title: 'VORTEX',
    brand: 'Deco Line',
    price: '1,054.00',
    isFree: true,
    views: 2140,
    downloads: 228,
    likes: 0,
    date: '26.10.2025',
  },
  {
    id: '2',
    image: '/images/model-chair.jpg',
    title: 'Office chair Epico Soft 519',
    brand: 'Polflex',
    price: '808.00',
    isFree: true,
    views: 4162,
    downloads: 1503,
    likes: 0,
    date: '19.10.2025',
  },
  {
    id: '3',
    image: '/images/model-sol.jpg',
    title: 'SOL B-82',
    brand: 'Wall Deco',
    price: '808.00',
    isFree: true,
    views: 2753,
    downloads: 223,
    likes: 0,
    date: '07.10.2025',
  },
  {
    id: '4',
    image: '/images/model-ceiling.jpg',
    title: '3D Ceiling coffers Acoustic KD4',
    brand: 'Fovere',
    price: '75.00',
    isFree: true,
    views: 1251,
    downloads: 42,
    likes: 0,
    date: '30.09.2025',
  },
  {
    id: '5',
    image: '/images/model-melody.jpg',
    title: 'SYMMETRIC MELODY B-66',
    brand: 'Wall Deco',
    price: '560.00',
    isFree: true,
    views: 3300,
    downloads: 619,
    likes: 0,
    date: '30.09.2025',
  },
  {
    id: '6',
    image: '/images/model-lamp.jpg',
    title: 'Acoustic lamp Roofy Arcus',
    brand: 'Fovere',
    price: '470.00',
    isFree: true,
    views: 2188,
    downloads: 351,
    likes: 0,
    date: '27.09.2025',
  },
  {
    id: '7',
    image: '/images/model-nature.jpg',
    title: 'SCENT OF NATURE B-65',
    brand: 'Wall Deco',
    price: '359.00',
    isFree: true,
    views: 3219,
    downloads: 622,
    likes: 0,
    date: '27.09.2025',
  },
  {
    id: '8',
    image: '/images/model-panel.jpg',
    title: 'Acoustic panel Openwork Azur A6',
    brand: 'Fovere',
    price: '440.00',
    isFree: true,
    views: 1287,
    downloads: 88,
    likes: 0,
    date: '27.09.2025',
  },
];

// Sample data for Scenes
const scenesData = [
  {
    id: '1',
    image: '/images/scene-ethnic.jpg',
    title: 'Ethnic studio',
    brand: 'Toon Project',
    isFree: false,
    credits: 53,
    views: 3151,
    downloads: 0,
    likes: 0,
    date: '07.10.2025',
  },
  {
    id: '2',
    image: '/images/scene-bedroom.jpg',
    title: 'Modern bedroom 153',
    brand: 'cooline',
    isFree: false,
    credits: 24,
    views: 77,
    downloads: 0,
    likes: 0,
    date: '05.12.2025',
  },
  {
    id: '3',
    image: '/images/scene-bathroom.jpg',
    title: 'Classic bathroom 4',
    brand: 'Yony Coaquira',
    isFree: false,
    credits: 18,
    views: 183,
    downloads: 0,
    likes: 0,
    date: '03.12.2025',
  },
  {
    id: '4',
    image: '/images/scene-neoclassical.jpg',
    title: 'Neoclassical bedroom 64',
    brand: 'Bekzod Jumaniyozov',
    isFree: false,
    credits: 25,
    views: 167,
    downloads: 0,
    likes: 0,
    date: '03.12.2025',
  },
  {
    id: '5',
    image: '/images/scene-bathroom2.jpg',
    title: 'Modern bathroom 156',
    brand: 'Unknown',
    isFree: false,
    credits: 15,
    views: 205,
    downloads: 0,
    likes: 0,
    date: '02.12.2025',
  },
  {
    id: '6',
    image: '/images/scene-childroom.jpg',
    title: 'Modern childroom 53',
    brand: 'Unknown',
    isFree: false,
    credits: 22,
    views: 233,
    downloads: 0,
    likes: 0,
    date: '02.12.2025',
  },
  {
    id: '7',
    image: '/images/scene-bedroom2.jpg',
    title: 'Neoclassical bedroom 63',
    brand: 'Unknown',
    isFree: false,
    credits: 23,
    views: 280,
    downloads: 0,
    likes: 0,
    date: '01.12.2025',
  },
  {
    id: '8',
    image: '/images/scene-house.jpg',
    title: 'Modern house',
    brand: 'Unknown',
    isFree: false,
    credits: 55,
    views: 281,
    downloads: 0,
    likes: 0,
    date: '28.11.2025',
  },
];

// Sample data for Textures
const texturesData = [
  {
    id: '1',
    image: '/images/texture-madreperla2.jpg',
    title: 'Tile Madreperla 2',
    brand: 'Unknown',
    isFree: true,
    views: 6240,
    downloads: 1044,
    likes: 0,
    date: '22.06.2025',
  },
  {
    id: '2',
    image: '/images/texture-madreperla1.jpg',
    title: 'Tile Madreperla 1',
    brand: 'Unknown',
    isFree: true,
    views: 6580,
    downloads: 1415,
    likes: 0,
    date: '22.06.2025',
  },
  {
    id: '3',
    image: '/images/texture-black1.jpg',
    title: 'Tile BLACK TEMPEST 1',
    brand: 'Unknown',
    isFree: true,
    views: 4751,
    downloads: 714,
    likes: 0,
    date: '22.06.2025',
  },
  {
    id: '4',
    image: '/images/texture-black4.jpg',
    title: 'Tile BLACK TEMPEST 4',
    brand: 'Unknown',
    isFree: true,
    views: 3884,
    downloads: 310,
    likes: 0,
    date: '22.06.2025',
  },
  {
    id: '5',
    image: '/images/texture-black3.jpg',
    title: 'Tile BLACK TEMPEST 3',
    brand: 'Unknown',
    isFree: true,
    views: 3636,
    downloads: 234,
    likes: 0,
    date: '22.06.2025',
  },
  {
    id: '6',
    image: '/images/texture-black2.jpg',
    title: 'Tile BLACK TEMPEST 2',
    brand: 'Unknown',
    isFree: true,
    views: 3370,
    downloads: 170,
    likes: 0,
    date: '22.06.2025',
  },
  {
    id: '7',
    image: '/images/texture-casablanca.jpg',
    title: 'Tile The Casablanca',
    brand: 'Unknown',
    isFree: true,
    views: 6407,
    downloads: 928,
    likes: 0,
    date: '26.02.2025',
  },
  {
    id: '8',
    image: '/images/texture-bars.jpg',
    title: 'Tile Sweet Bars',
    brand: 'Unknown',
    isFree: true,
    views: 12182,
    downloads: 3100,
    likes: 0,
    date: '26.02.2025',
  },
];

// Sample data for Works
const worksData = [
  {
    id: '1',
    image: '/images/work-magnit.jpg',
    title: 'Magnit store',
    brand: 'Unknown',
    isFree: true,
    views: 341,
    downloads: 2,
    likes: 0,
    date: '2025-01-01',
  },
  {
    id: '2',
    image: '/images/work-livingroom.jpg',
    title: 'Livingroom',
    brand: 'Unknown',
    isFree: true,
    views: 785,
    downloads: 8,
    likes: 0,
    date: '2025-01-01',
  },
  {
    id: '3',
    image: '/images/work-student.jpg',
    title: 'student project',
    brand: 'Unknown',
    isFree: true,
    views: 842,
    downloads: 7,
    likes: 0,
    date: '2025-01-01',
  },
  {
    id: '4',
    image: '/images/work-bedroom.jpg',
    title: 'Minimalism Bedroom',
    brand: 'Unknown',
    isFree: true,
    views: 1100,
    downloads: 23,
    likes: 0,
    date: '2025-01-01',
  },
];

export default function Home() {
  return (
    <div className="min-h-screen bg-white">
      <Header />
      <HeroSection />
      <ProductSection title="New Models" products={modelsData} />
      <ProductSection title="New Scenes" products={scenesData} />
      <ProductSection title="New Textures" products={texturesData} />
      <ProductSection title="New Works" products={worksData} />
      <Footer />
    </div>
  );
}
